### PR TITLE
Replace unicode char from pnglib to String.formCarCode

### PR DESCRIPTION
**Pull request by redboul**
Hi,

We are using Tomcat servlet container to serve our application but there is some issues with tomcat managing the unicode characters inside the pnglib.js file.
I replace the unicode encode character with JavaScript method that allows to have the same result.

Regards

### CODE REVIEW

**Comment by redboul** [comment]
up !

**Comment by stewartlord** [comment]
Hi @redboul, sorry for the poor response time. I'm confused as to why these characters would cause problems for Tomcat. From here the characters don't appear to be unicode, but rather octal escape sequences. I'm really curious now, what is the issue with Tomcat?

**Comment by redboul** [comment]
Actually, I said Tomcat because it was significant to us that the following issue is only happening on this application server (it does not occur on Jetty), but it can come from a step in our build process that I am missing.
In the minified files from Jetty, the pnglib part looks "normal" : `"PNG\r\n\n" + this.buffer.join("")` 
pnglib-jetty-encoding. 
But from Tomcat, there is a strange start character: `"Â‰PNG\r\n\n" + this.buffer.join("")` 
pnglib-tomcat-encoding

It does not happen if we apply the fix.

It may also come from some different encoding management in the two environment.

**Comment by redboul** [comment]
up !

**Comment by stewartlord** [comment]
Do you mind trying these as hex escapes instead? I think that would be `\x89` and `\x1A`?

**Comment by stewartlord** [comment]
@redboul bump for trying the hex escapes :smile:

**Comment by stewartlord** [comment]
Bump!

**Pull request closed without merging**
